### ISSUE TITLE
Add KV17 NotMonitored to tracked faulty AVL

### ISSUE THREAD

**Issue by skinkie** [StichtingOpenGeo/openebs2#124]
![image](https://user-images.githubusercontent.com/502394/79472611-560ae300-8004-11ea-862c-81fc48a6bd6e.png)

**Comment by skinkie** [comment]
![image](https://user-images.githubusercontent.com/502394/79760980-210ed100-8321-11ea-962e-9d5e202bd243.png)

**Comment by Baasje85** [comment]
![screenshot NotMonitored](https://user-images.githubusercontent.com/51262792/79975487-5b03e280-849b-11ea-9753-de33684fe0b7.png)
