### ISSUE TITLE
Handle trips after midnight correctly

### ISSUE THREAD

**Issue by joelhaasnoot** [StichtingOpenGeo/openebs2#32]
We currently always show trips from the current operatingday. After midnight, that's tomorrow, so the operator may accidentally remove tomorrow evenings' trips.

**Comment by Baasje85** [comment]
I believe this issue has been solved with:

![image](https://user-images.githubusercontent.com/51262792/106599594-94549d00-6559-11eb-9f99-5ca18576f2f7.png)

In addition, trips after midnight are shown at the bottom of the journey list of the current selected operatingday (with +1)
