### ISSUE TITLE
Show date of last KV1 import

### ISSUE THREAD

**Issue by henkschuurman** [StichtingOpenGeo/openebs2#44]
I would like to be able to see which date the last KV1 import is made.

**Comment by Baasje85** [comment]
I placed the importstatus below the importstatus calendar. Picture below shows what it will look like after my fix (only the last five imports will be shown here). 
NB: the status 'Er waren 102 fouten' is fictional, but if there are errors, this is what it will say (apart from a different number of course...)

![image](https://user-images.githubusercontent.com/51262792/80968557-761a0f00-8e18-11ea-8f6a-044a3291abca.png)
