### ISSUE TITLE
Empty messagendtime results in rejection without notification

### ISSUE THREAD

**Issue by skywave** [StichtingOpenGeo/openebs2#49]
Reproduce

1 Select stops
2 Add random text
3 Remove endtime (empty form)
4 Press enter or click publish
5 Page goes back to message overview, nothing happens.

**Comment by Baasje85** [comment]
When I remove the messageendtime in the form and press 'send', this is the result:

![image](https://user-images.githubusercontent.com/51262792/80805963-b16ad280-8bb9-11ea-91f7-8ddc449c8535.png)

I believe this was already fixed.
