### ISSUE TITLE
KV17 sort is by linenumber

### ISSUE THREAD

**Issue by joelhaasnoot** [StichtingOpenGeo/openebs2#65]
Should be by publiclinenumber, some lines are repeated this way. Also show direction of the trip.
![openebsbug-lijn4](https://f.cloud.github.com/assets/592662/1827449/c8e6e9bc-7234-11e3-80a9-0a505c04b0c5.png)

**Comment by Baasje85** [comment]
Seems to me it's already fixed like the screenshot Joel provided. At this moment it looks like this:

![image](https://user-images.githubusercontent.com/51262792/80806992-55557d80-8bbc-11ea-986e-757d22646ebc.png)
