### ISSUE TITLE
XML rejected due to messagestarttime incorrect format

### ISSUE THREAD

**Issue by skywave** [StichtingOpenGeo/openebs2#91]
Should we allow messagestarttime to be empty?

'''
[26/Mar/2014 12:39:58] DEBUG [openebs.push:62] <?xml version="1.0" ?>
<VV_TM_PUSH xmlns="http://bison.connekt.nl/tmi8/kv15/msg">

```
<SubscriberID>openov</SubscriberID>


<Version>BISON 8.1.0.0</Version>


<DossierName>KV15messages</DossierName>


<Timestamp>2014-03-26T11:39:57.748037+00:00</Timestamp>


<KV15messages>


    <STOPMESSAGE>

        <dataownercode>HTM</dataownercode>

        <messagecodedate>2014-03-26</messagecodedate>

        <messagecodenumber>2</messagecodenumber>

        <userstopcodes>

            <userstopcode>2607</userstopcode>

            <userstopcode>2606</userstopcode>

        </userstopcodes>

        <messagepriority>PTPROCESS</messagepriority>

        <messagetype>OVERRULE</messagetype>

        <messagedurationtype>ENDTIME</messagedurationtype>

        <messagestarttime/>

        <messageendtime/>

        <messagecontent>Testbericht</messagecontent>

        <messagetimestamp>2014-03-26T12:39:57.885805+01:00</messagetimestamp>
    </STOPMESSAGE>


</KV15messages>
```

</VV_TM_PUSH>

[26/Mar/2014 12:39:58] DEBUG [openebs.push:68] Posting to govi (dris-pro.transmodel.nl//TMI_Post/KV15)
[26/Mar/2014 12:39:59] DEBUG [openebs.push:86] Connecting to govi and got response code 200 and content: <?xml version="1.0"?>

<tmi8:VV_TM_RES xmlns:tmi8="http://bison.connekt.nl/tmi8/kv15/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv6/core" >
    tmi8:SubscriberIDopenOV/tmi8:SubscriberID
    tmi8:VersionBISON 8.1.0.0/tmi8:Version
    tmi8:DossierNameKV15messages/tmi8:DossierName
    tmi8:Timestamp2014-03-26T12:39:59+01:00/tmi8:Timestamp
    tmi8:ResponseCodeNA/tmi8:ResponseCode
    tmi8:ResponseErrorXSD error: Element '{http://bison.connekt.nl/tmi8/kv15/msg}messagestarttime': '' is not a valid value of the atomic type '{http://bison.connekt.nl/tmi8/kv15/msg}tmidatetimeType'.
 at line 42
Element '{http://bis/tmi8:ResponseError
/tmi8:VV_TM_RES
[26/Mar/2014 12:39:59] ERROR [openebs.views.mixins:47] Push to govi failed with code 200: XSD error: Element '{http://bison.connekt.nl/tmi8/kv15/msg}messagestarttime': '' is not a valid value of the atomic type '{http://bison.connekt.nl/tmi8/kv15/msg}tmidatetimeType'.
 at line 42
Element '{http://bis

'''

**Comment by Baasje85** [comment]
Output in XML looks like this (at the moment). Is this issue still active or already resolved?

<STOPMESSAGE>
   <dataownercode>HTM</dataownercode>
   <messagecodedate>2020-05-01</messagecodedate>
   <messagecodenumber>5004</messagecodenumber>
   <userstopcodes>
      <userstopcode>8122</userstopcode>
   </userstopcodes>
   <messagepriority>PTPROCESS</messagepriority>
   <messagetype>GENERAL</messagetype>
   <messagedurationtype>ENDTIME</messagedurationtype>
   <messagestarttime>2020-05-01T13:50:05+02:00</messagestarttime>
   <messageendtime>2020-05-02T04:00:00+02:00</messageendtime>
   <messagecontent>test</messagecontent>
   <messagetimestamp>2020-05-01T13:50:14.395493+02:00</messagetimestamp>
</STOPMESSAGE>

**Comment by Baasje85** [comment]
At the moment the xml-output looks like the one below. Is the issue still active or already resolved?

```xml
<STOPMESSAGE>
   <dataownercode>HTM</dataownercode>
   <messagecodedate>2020-05-01</messagecodedate>
   <messagecodenumber>5004</messagecodenumber>
   <userstopcodes>
      <userstopcode>8122</userstopcode>
   </userstopcodes>
   <messagepriority>PTPROCESS</messagepriority>
   <messagetype>GENERAL</messagetype>
   <messagedurationtype>ENDTIME</messagedurationtype>
   <messagestarttime>2020-05-01T13:50:05+02:00</messagestarttime>
   <messageendtime>2020-05-02T04:00:00+02:00</messageendtime>
   <messagecontent>test</messagecontent>
   <messagetimestamp>2020-05-01T13:50:14.395493+02:00</messagetimestamp>
</STOPMESSAGE>
```
